<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.028" timestamp="2022-02-09T16:38:14.693863" hostname="medplus-OptiPlex-3050">
<testcase classname="test_multiplication" name="test_multiplication_11[1-11]" time="0.001" />
<testcase classname="test_multiplication" name="test_multiplication_11[2-22]" time="0.001" />
<testcase classname="test_multiplication" name="test_multiplication_11[3-35]" time="0.001">
<failure message="assert 33 == 35&#10;  +33&#10;  -35">num = 3, output = 35

    @pytest.mark.parametrize("num, output",[(1,11),(2,22),(3,35),(4,44)])
    def test_multiplication_11(num, output):
&gt;      assert 11*num == output
E      assert 33 == 35
E        +33
E        -35

test_multiplication.py:5: AssertionError</failure>
</testcase><testcase classname="test_multiplication" name="test_multiplication_11[4-44]" time="0.001" />
</testsuite>
</testsuites>
